# Setup
title: hulu-knight
description: my own website
url: https://hulu-knight.github.io
avatar: /IMG_7796.JPG
permalink: pretty
cover_image: /bg.jpeg

# Gems
plugins:
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap

# Optimize Jekyll
exclude: 
  - .editorconfig
  - .git
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md
  - scripts/
  - not-pure-poole.gemspec

# Optimize Jekyl SEO Tag
twitter:
  username: hulu-knight
  card: summary
logo: logo.png
social:
  name: hulu-knight
  links:
    - https://twitter.com/hulu-knight
    - https://github.com/hulu-knight
google_site_verification: xxxxx
lang: ch

sass:
  sass_dir: _sass
  style: :compressed

# Options

# Replace this value and uncomment to enable Google Analytics tracking
# google_analytics: UA-000000-0

# Replace this value and uncomment to enable Disqus
# disqus: xxxxxx

# Specify the author for blog posts
author:
  name: hulu-knight
  url: https://github.com/hulu-knight/
  email: wheezyknight@gmail.com
